import { createElement } from 'lwc';
import TaskModal from 'c/taskModal';

describe('c-task-modal', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('propogates close event on clicking close button', () => {
        const element = createElement('c-task-modal', {
            is: TaskModal
        });
        element.mode = 'edit';
        element.task = {
            "description": "Task 1 Description",
            "taskId": "a010R000008NirsQAC",
            "taskName": "Task 1"
          };
        element.objectApiName='To_Do_Task__c';
        element.fields=['Name', 'Description__c'];
        document.body.appendChild(element);

        // Listen for delete task event
        const handler = jest.fn();
        element.addEventListener('cancelmodal', handler);

        return Promise.resolve().then(() => {
            // Click close button
            const closeButton = element.shadowRoot.querySelector('.close-button');
            closeButton.click();
        }).then(() => {
            expect(handler).toBeCalled();
        })
    });

    it('propogates close event on clicking reset button', () => {
        const element = createElement('c-task-modal', {
            is: TaskModal
        });
        element.mode = 'edit';
        element.task = {
            "description": "Task 1 Description",
            "taskId": "a010R000008NirsQAC",
            "taskName": "Task 1"
          };
        element.objectApiName='To_Do_Task__c';
        element.fields=['Name', 'Description__c'];
        document.body.appendChild(element);

        // Listen for delete task event
        const handler = jest.fn();
        element.addEventListener('cancelmodal', handler);

        return Promise.resolve().then(() => {
            // Click close button
            const resetButton = element.shadowRoot.querySelector('.reset-button');
            resetButton.click();
        }).then(() => {
            expect(handler).toBeCalled();
        })
    });

    it('sets New Task as title in create mode', () => {
        const element = createElement('c-task-modal', {
            is: TaskModal
        });
        element.mode = 'create';
        element.objectApiName='To_Do_Task__c';
        element.fields=['Name', 'Description__c'];
        document.body.appendChild(element);

        return Promise.resolve().then(() => {
            // Check modal title
            const modalTitle = element.shadowRoot.querySelector('h2[data-id="modal-heading-01"]');
            expect(modalTitle.textContent).toBe('New Task');
        });
    });

    it('sets task title as title in edit mode', () => {
        const element = createElement('c-task-modal', {
            is: TaskModal
        });
        element.mode = 'create';
        element.task = {
            "description": "Task 1 Description",
            "taskId": "a010R000008NirsQAC",
            "taskName": "Task 1"
          };
        element.objectApiName='To_Do_Task__c';
        element.fields=['Name', 'Description__c'];
        document.body.appendChild(element);

        return Promise.resolve().then(() => {
            // Check modal title
            const modalTitle = element.shadowRoot.querySelector('h2[data-id="modal-heading-01"]');
            expect(modalTitle.textContent).not.toBe('New Task');
            expect(modalTitle.textContent).toBe(element.task.taskName);
        });
    });


    // it('TODO: test case generated by CLI command, please fill in test logic', () => {
    //     const element = createElement('c-task-modal', {
    //         is: TaskModal
    //     });
    //     document.body.appendChild(element);
    //     expect(1).toBe(2);
    // });
});